name: Delete old Packages and Caches

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight, utc
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old packages and caches
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.TOKEN }}
          image-names: 'cretu.dev pertermann.de nextjs-cretu'
          image-tags: '!latest'
          cut-off: 2m
          keep-n-most-recent: 5
          dry-run: false
      # Do other steps like checkout, install, compile, etc.
      - uses: MyAlbum/purge-cache@v2
        with:
          accessed: true # Purge caches by their last accessed time (default)
          created: false # Purge caches by their created time (default)
          max-age: 604800 # Leave only caches accessed in the last 7 days (default)