name: Remove package versions
on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with: 
          owner: 'github'
          package-name: 'test-package'
          package-type: 'npm'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 3
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'