on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight, utc
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: PrtmPhlp
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "cretu.dev"
          image-tags: "!latest"
          cut-off: 1h
          keep-n-most-recent: 5
          dry-run: true