
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yarn Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    env:
      HOME: /root/

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      #- name: Use Node.js
        #uses: actions/setup-node@v3
      #  with:
      #    node-version: '20.x'
          #cache: 'yarn'
      - name: Install dependencies
        run: bun install
      - name: Run Test
        run: bun run test
      - name: Build Website
        run: bun run build
      - name: Copy Files
        run: /usr/bin/rsync -ah --delete /root/actions-runner/work-cretu/cretu.dev/cretu.dev/. /root/work-clone/
      - name: Reload Server
        run: cd /root/work-clone && /usr/local/bin/pm2 restart cretu
