
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yarn Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    env:
      HOME: ${{ secrets.SERVER_HOME }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      #- name: Use Node.js
        #uses: actions/setup-node@v3
      #  with:
      #    node-version: '20.x'
          #cache: 'yarn'
      - name: Install dependencies
        run: bun install
      - name: Run Test
        run: bun run test
      - name: Build Website
        run: bun run build
      - shell: bash
        name: Rsync
        env:
          RUNNER_WORK_LOCATION: ${{ secrets.RUNNER_WORK_LOCATION }}
          SERVER_LOCATION: ${{ secrets.SERVER_DEPLOY_LOCATION }}
        run: |
          /usr/bin/rsync -ah --delete $RUNNER_WORK_LOCATION $SERVER_LOCATION
      # - name: Copy Files
        # run: /usr/bin/rsync -ah --delete ${{ secrets.RUNNER_WORK_LOCATION }}/cretu.dev/cretu.dev/. ${{ secrets.SERVER_LOCATION }}
      - shell: bash
        name: Reload Server
        env:
          SERVER_LOCATION: ${{ secrets.SERVER_DEPLOY_LOCATION }}
        run: |
          cd $secrets.SERVER_DEPLOY_LOCATION && /usr/local/bin/pm2 restart cretu
