name: 'GH: Bun Build'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # install
      - name: Install Dependencies
        run: bun install
      - name: Run Test
        run: bun run test
      - name: Build Website
        run: bun run build
